/* lib/unit.js
 *
 * The systemd user unit we generate for brscan-skey, and where the binary it
 * runs lives.
 *
 * Kept out of lib/skey.js: that module imports the shell's extension resource
 * for gettext, and this one has to load under plain gjs as well —
 * scripts/systemd-probe.js generates the same unit outside any shell.
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 */

import GLib from 'gi://GLib';

export const UNIT_NAME = 'brscan-skey.service';

/** Path to the brscan-skey wrapper, or null when it is not installed. */
export function findBinary() {
    return GLib.find_program_in_path('brscan-skey');
}

/**
 * The generated unit file.
 *
 * @param {string} binary path to the brscan-skey wrapper
 * @returns {string} contents of ~/.config/systemd/user/brscan-skey.service
 */
export function unitText(binary) {
    return `# ${UNIT_NAME} — generated by the Brother MFC GNOME Shell extension.
#
# There is deliberately no [Install] section, and it is not an oversight.
#
# The systemd user manager on this machine is shared between the GNOME and the
# sway session and runs with Linger=yes, so anything reachable from
# graphical-session.target is started under sway as well — where there is no
# GNOME session for brscan-skey to report a scan to. ConditionEnvironment= does
# not save it either: SWAYSOCK goes stale under lingering, and
# XDG_CURRENT_DESKTOP only matches exactly while sway sets "sway:wlroots".
#
# Without [Install] this unit stays "static": it is in no .wants directory,
# nothing pulls it in, and "systemctl --user enable ${UNIT_NAME}" answers with
# an explanation and changes nothing, instead of quietly dropping a symlink into
# graphical-session.target.wants. The extension starts and stops it over
# org.freedesktop.systemd1 from enable() and disable(); the extension only runs
# under GNOME, so its lifetime already is the scope wanted.
#
# See docs/design.md §2.4. Hand edits are overwritten: the extension rewrites
# this file whenever it differs from what it generates.

[Unit]
Description=Brother brscan-skey scan key daemon
Documentation=https://github.com/jeanparpaillon/brother-mfc-gnome-extension

[Service]
Type=simple
# -f matters: without it the wrapper backgrounds brscan-skey-exe and returns,
# leaving systemd supervising a shell that has already exited.
ExecStart=${binary} -f
Restart=on-failure
RestartSec=5
`;
}
